const fs = require('fs');
const path = require('path');

function walkDir(dir, callback) {
    if (dir.includes('node_modules') || dir.includes('.git') || dir.includes('build') || dir.includes('dist')) return;
    try {
        fs.readdirSync(dir).forEach(f => {
            let dirPath = path.join(dir, f);
            let isDirectory = fs.statSync(dirPath).isDirectory();
            isDirectory ? walkDir(dirPath, callback) : callback(dirPath);
        });
    } catch (e) { }
}

function removeComments(filePath) {
    if (!filePath.endsWith('.jsx') && !filePath.endsWith('.js')) return;

    let content = fs.readFileSync(filePath, 'utf8');

    // Remove {/* ... */} structural AI comments
    content = content.replace(/^[ \t]*\{\/\*.*?\*\/}[ \t]*\r?\n/gm, '');
    content = content.replace(/\{\/\*.*?\*\/\}/g, '');

    // Remove simple // comments that start a line (optional: we can leave them if they are useful, but user said "remove all the comments generated by the ai or right human like comments instead")
    // Let's only remove structural JSX comments and trailing // comments if they clearly look AI generated like "// Rename states", "// LIST VIEW", etc. Actually stripping all // comments might be risky for imports etc? // is safe to remove if it's on a line by itself.
    content = content.replace(/^[ \t]*\/\/.*?\r?\n/gm, '');

    fs.writeFileSync(filePath, content);
}

walkDir(path.join(__dirname, 'src'), removeComments);
walkDir(path.join(__dirname, '../server'), removeComments);
console.log('Comments removed.');
